server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #注册中心动态路由

      routes:
         - id: payment_routh  #路由的名称，没有确定的规则，但是要求唯一
           #uri: http://localhost:8001 #匹配后提供服务的路由地址
           uri: lb://cloud-payment-service
           predicates:
            - Path=/payment/get/** #断言，路径相匹配之后进行路由
           # - After=2020-09-27T11:50:23.523+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
           # - Header=X-Request-Id,\d+

         - id: payment_routh2  #路由的名称，没有确定的规则，但是要求唯一
           #uri: http://localhost:8001 #匹配后提供服务的路由地址
           uri: lb://cloud-payment-service
           predicates:
            - Path=/payment/lb/** #断言，路径相匹配之后进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
   service-url:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://eureka7001.com:7001/eureka

